### ISSUE TITLE
Option to modify Boilerplate

### ISSUE THREAD

**Issue by SirTwsted** [sidthesloth92/vsc_html5_boilerplate#10] opened 2019-03-22 08:21 UTC
Please give us the Option to modify Boilerplate.
I cant seem to find it anywhere. Im hammering my search in windows and it cant find anything
in regards to HTML Boilerplate.
thx

**Comment by bryanmobrien** [comment] 2019-08-15 04:19
If you want to modify the html5_boilerplate, I believe you have to edit html.json for your particular environment.  (I suggest copying the original ;-) ).  I guess you could uninstall and reinstall if you screw it up (like I did the first time).

You can edit the file located in your extensions directory.  In my setup, I edited:

`/Users/ob/.vscode/extensions/sidthesloth.html5-boilerplate-1.0.3/snippets/html.json`

Pay attention to the " and the \t (tabs) in your html.json file.

I used it to add bootstrap, jquery and popper CDNs to my boilerplate.  I'm very new to web development, but this extension saves me a ton of time.  Thank you, sidthesloth92.

See: 
`https://github.com/sidthesloth92/vsc_html5_boilerplate/blob/master/snippets/html.json`

**Comment by MarkCorder** [comment] 2019-08-16 14:34
Thanks bryanmobrien - I was looking for where to edit this myself. I wanted to add a link to Browse Happy to the "update your browser" warning...

**Comment by sidthesloth92** [comment] 2020-09-28 08:23
Closing the issue as the extension is working as intended.

**Closed by sidthesloth92** 2020-09-28 08:23 UTC
